server:
  port: 8090

spring:
  application:
    name: user-microservice-foodcourt
  datasource:
    url:
    username: postgres
    password: ${DB_FOODCOURT_USERS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update